# Generated by Django 5.2.6 on 2025-10-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_and_module_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='course_and_module_app.module')),
                ('material', models.ManyToManyField(blank=True, related_name='materials', to='lessons_app.material')),
            ],
        ),
    ]
