# Generated by Django 5.2.6 on 2025-12-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_and_module_app', '0001_initial'),
        ('tasksmarks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='course_and_module_app.module')),
                ('tasks', models.ManyToManyField(blank=True, related_name='task_in_lesson', to='tasksmarks_app.task')),
                ('tasks_test', models.ManyToManyField(blank=True, related_name='test_task_in_lesson', to='tasksmarks_app.testtask')),
                ('material', models.ManyToManyField(blank=True, related_name='material_in_lesson', to='lessons_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lessons', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons_app.lesson')),
            ],
        ),
    ]
