# Generated by Django 5.2.6 on 2025-11-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0002_lessonschedule'),
        ('tasksmarks_app', '0005_alter_choicetask_choice_alter_choicetest_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_in_lesson', to='tasksmarks_app.task'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='material_in_lesson', to='lessons_app.material'),
        ),
    ]
