# Generated by Django 5.2.6 on 2025-11-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0003_lesson_tasks_alter_lesson_material'),
        ('tasksmarks_app', '0008_remove_task_user_answer_answertask_delete_choicetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tasks_test',
            field=models.ManyToManyField(blank=True, related_name='test_task_in_lesson', to='tasksmarks_app.testtask'),
        ),
    ]
