# Generated by Django 5.2.6 on 2025-10-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_and_module_app', '0002_module_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_module', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to='course_and_module_app.module')),
            ],
        ),
    ]
