# Generated by Django 5.2.6 on 2025-12-05 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('un_check', 'Un check'), ('well', 'Well Done!'), ('wrong', 'Wrong, try again')], default='todo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('well', 'Well Done!'), ('wrong', 'Wrong, try again')], default='todo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_task', to=settings.AUTH_USER_MODEL, verbose_name='Вибір студента')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_task', to='tasksmarks_app.task', verbose_name='Збереження завдання')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Варіант')),
                ('is_correct', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasksmarks_app.testtask', verbose_name='Завдання')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_choice', to=settings.AUTH_USER_MODEL, verbose_name='Вибір студента')),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_choices', to='tasksmarks_app.option', verbose_name='Вибір тесту')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_test', to='tasksmarks_app.testtask', verbose_name='Збереження тесту')),
            ],
        ),
    ]
