# Generated by Django 5.2.6 on 2025-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('un_check', 'Un check'), ('well', 'Well Done!'), ('wrong', 'Wrong, try again')], default='un_check', max_length=20),
        ),
    ]
