# Generated by Django 5.2.6 on 2025-10-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasksmarks_app.testtask', verbose_name='Завдання'),
        ),
    ]
