# Generated by Django 5.2.6 on 2025-10-04 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0002_option_is_correct_alter_option_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в ')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_task', to='tasksmarks_app.testtask', verbose_name='Збереження відповіді')),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_choices', to='tasksmarks_app.option', verbose_name='Вибір тесту')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_choice', to=settings.AUTH_USER_MODEL, verbose_name='Вибір студента')),
            ],
        ),
    ]
