# Generated by Django 5.2.6 on 2025-10-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0003_choicetest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetest',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_test', to='tasksmarks_app.testtask', verbose_name='Збереження відповіді'),
        ),
        migrations.CreateModel(
            name='ChoiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в ')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_task', to='tasksmarks_app.task', verbose_name='Збереження відповіді')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_task', to=settings.AUTH_USER_MODEL, verbose_name='Вибір студента')),
            ],
        ),
    ]
