# Generated by Django 5.2.6 on 2025-10-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0004_alter_choicetest_choice_choicetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetask',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_task', to='tasksmarks_app.task', verbose_name='Збереження завдання'),
        ),
        migrations.AlterField(
            model_name='choicetest',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_test', to='tasksmarks_app.testtask', verbose_name='Збереження тесту'),
        ),
    ]
