# Generated by Django 5.2.6 on 2025-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0005_alter_choicetask_choice_alter_choicetest_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
