# Generated by Django 5.2.6 on 2025-11-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0006_task_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='answer',
            new_name='user_answer',
        ),
    ]
