# Generated by Django 5.2.6 on 2025-11-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmarks_app', '0007_rename_answer_task_user_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_answer',
        ),
        migrations.CreateModel(
            name='AnswerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в ')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_task', to='tasksmarks_app.task', verbose_name='Збереження завдання')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_task', to=settings.AUTH_USER_MODEL, verbose_name='Вибір студента')),
            ],
        ),
        migrations.DeleteModel(
            name='ChoiceTask',
        ),
    ]
